version: '3.3'

services:
  pgsql:
    container_name: postgres-container
    image: postgres:alpine
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: dbmaster
      POSTGRES_DB: postgres
    volumes:
      - /var/lib/postgresql/data:/var/lib/postgresql/data
      - /init-db.sh:/docker-entrypoint-initdb.d/
    ports:
      - 5432:5432
    networks:
      - figaroo-network

  pgadmin:
    container_name: pgadmin4-container
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: 'dnk_vip@hotmail.com'
      PGADMIN_DEFAULT_PASSWORD: 'omega3ab'
    ports:
      - 8080:80
    depends_on:
      - pgsql
    networks:
      - figaroo-network

  app-dev:
    container_name: figaroo-dev-container
    image: docker.io/andrelbraga/figaroo-dev
    environment:
      NODE_ENV: development
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 3000:3000
    networks:
      - figaroo-network
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    restart: unless-stopped
    depends_on:
      - pgsql
  
  app-web:
    container_name: figaroo-pwa-container
    image: docker.io/andrelbraga/figaroo-pwa
    ports:
      - 80:80
    networks:
      - figaroo-network
    restart: unless-stopped
    depends_on:
      - app-dev
      - pgsql

networks:
  figaroo-network:
    driver: bridge
